# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'About.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_About(object):
    def setupUi(self, About):
        About.setObjectName("About")
        About.resize(346, 205)
        self.centralwidget = QtWidgets.QWidget(About)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 40, 321, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.buttonVisitLinkedin = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.buttonVisitLinkedin.setGeometry(QtCore.QRect(100, 70, 211, 41))
        self.buttonVisitLinkedin.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonVisitLinkedin.setCheckable(False)
        self.buttonVisitLinkedin.setObjectName("buttonVisitLinkedin")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 10, 221, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.buttonVisitGithub = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.buttonVisitGithub.setGeometry(QtCore.QRect(100, 110, 201, 51))
        self.buttonVisitGithub.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonVisitGithub.setCheckable(False)
        self.buttonVisitGithub.setObjectName("buttonVisitGithub")
        About.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(About)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 346, 21))
        self.menubar.setObjectName("menubar")
        self.menuCalculator = QtWidgets.QMenu(self.menubar)
        self.menuCalculator.setObjectName("menuCalculator")
        self.menuConverter = QtWidgets.QMenu(self.menubar)
        self.menuConverter.setObjectName("menuConverter")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        About.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(About)
        self.statusbar.setObjectName("statusbar")
        About.setStatusBar(self.statusbar)
        self.actionSimple = QtWidgets.QAction(About)
        self.actionSimple.setObjectName("actionSimple")
        self.actionAdvanced = QtWidgets.QAction(About)
        self.actionAdvanced.setObjectName("actionAdvanced")
        self.menuCalculator.addAction(self.actionSimple)
        self.menuCalculator.addAction(self.actionAdvanced)
        self.menubar.addAction(self.menuCalculator.menuAction())
        self.menubar.addAction(self.menuConverter.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(About)
        QtCore.QMetaObject.connectSlotsByName(About)

    def retranslateUi(self, About):
        _translate = QtCore.QCoreApplication.translate
        About.setWindowTitle(_translate("About", "About"))
        self.label.setText(_translate("About", "This app was developed by Filip Juračić"))
        self.buttonVisitLinkedin.setText(_translate("About", "Visit my LinkedIn"))
        self.label_2.setText(_translate("About", "CALCULATOR v1.0"))
        self.buttonVisitGithub.setText(_translate("About", "Visit my GitHub"))
        self.menuCalculator.setTitle(_translate("About", "Calculator"))
        self.menuConverter.setTitle(_translate("About", "Converter"))
        self.menuAbout.setTitle(_translate("About", "About"))
        self.actionSimple.setText(_translate("About", "Simple"))
        self.actionAdvanced.setText(_translate("About", "Advanced"))
